module.exports = [
    {
        controller:"CompanyController",
        service:"CompanyService",
        paths:[{method:'delete',path:'/CompanyServices/company',endpoint:'index'}]
    },
    {
        controller:"DepartmentController",
        service:"DepartmentService",
        paths:[
            {method:'get',path:'/CompanyServices/departments',endpoint:'index'},
            {method:'post',path:'/CompanyServices/department',endpoint:'create'},
            {method:'get',path:'/CompanyServices/department',endpoint:'retrieve'},
            {method:'put',path:'/CompanyServices/department',endpoint:'update'},
            {method:'delete',path:'/CompanyServices/department',endpoint:'delete'}
        ]
    },
    {
        controller:"EmployeeController",
        service:"EmployeeService",
        paths:[
            {method:'get',path:'/CompanyServices/employees',endpoint:'index'},
            {method:'post',path:'/CompanyServices/employee',endpoint:'create'},
            {method:'get',path:'/CompanyServices/employee',endpoint:'retrieve'},
            {method:'put',path:'/CompanyServices/employee',endpoint:'update'},
            {method:'delete',path:'/CompanyServices/employee',endpoint:'delete'}
        ]
    },
    {
        controller:"TimecardController",
        service:"TimecardService",
        paths:[
            {method:'get',path:'/CompanyServices/timecards',endpoint:'index'},
            {method:'post',path:'/CompanyServices/timecard',endpoint:'create'},
            {method:'get',path:'/CompanyServices/timecard',endpoint:'retrieve'},
            {method:'put',path:'/CompanyServices/timecard',endpoint:'update'},
            {method:'delete',path:'/CompanyServices/timecard',endpoint:'delete'}
        ]
    }
];
